export const modalTypes = {
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  TOGGLE_LANDING_MODAL: "TOGGLE_LANDING_MODAL",
  INITIALISE_MODAL_REDUCER: "INITIALISE_MODAL_REDUCER",
};

export const authTypes = {
  REGISTER_USER_REQUEST: "REGISTER_USER_REQUEST",
  REGISTER_USER_SUCCESS: "REGISTER_USER_SUCCESS",
  REGISTER_USER_FAILURE: "REGISTER_USER_FAILURE",
  AUTHENTICATE_USER_REQUEST: "AUTHENTICATE_USER_REQUEST",
  AUTHENTICATE_USER_SUCCESS: "AUTHENTICATE_USER_SUCCESS",
  AUTHENTICATE_USER_FAILURE: "AUTHENTICATE_USER_FAILURE",
  LOAD_USER_REQUEST: "LOAD_USER_REQUEST",
  LOAD_USER_SUCCESS: "LOAD_USER_SUCCESS",
  LOAD_USER_FAILURE: "LOAD_USER_FAILURE",
  USER_LOGGED_OUT: "USER_LOGGED_OUT",
};

export const alertTypes = {
  ALERT_ADDED: "ALERT_ADDED",
  ALERT_REMOVED: "ALERT_REMOVED",
};

export const profileTypes = {
  LOAD_PROFILE_REQUEST: "LOAD_PROFILE_REQUEST",
  LOAD_PROFILE_SUCCESS: "LOAD_PROFILE_SUCCESS",
  LOAD_PROFILE_FAILURE: "LOAD_PROFILE_FAILURE",
  INITIALISE_PROFILE_REDUCER: "INITIALISE_PROFILE_REDUCER",
};

export const postTypes = {
  LOAD_POSTS_REQUEST: "LOAD_POSTS_REQUEST",
  LOAD_POSTS_SUCCESS: "LOAD_POSTS_SUCCESS",
  LOAD_POSTS_FAILURE: "LOAD_POSTS_FAILURE",
  ADD_POST_REQUEST: "ADD_POST_REQUEST",
  ADD_POST_SUCCESS: "ADD_POST_SUCCESS",
  ADD_POST_FAILURE: "ADD_POST_FAILURE",
  DELETE_POST_REQUEST: "DELETE_POST_REQUEST",
  DELETE_POST_SUCCESS: "DELETE_POST_SUCCESS",
  DELETE_POST_FAILURE: "DELETE_POST_FAILURE",
  INITIALISE_POST_REDUCER: "INITIALISE_POST_REDUCER",
};

export const commentTypes = {
  ADD_COMMENT_REQUEST: "ADD_COMMENT_REQUEST",
  ADD_COMMENT_SUCCESS: "ADD_COMMENT_SUCCESS",
  ADD_COMMENT_FAILURE: "ADD_COMMENT_FAILURE",
  DELETE_COMMENT_REQUEST: "DELETE_COMMENT_REQUEST",
  DELETE_COMMENT_SUCCESS: "DELETE_COMMENT_SUCCESS",
  DELETE_COMMENT_FAILURE: "DELETE_COMMENT_FAILURE",
};

export const likeTypes = {
  ADD_LIKE_REQUEST: "ADD_LIKE_REQUEST",
  ADD_LIKE_SUCCESS: "ADD_LIKE_SUCCESS",
  ADD_LIKE_FAILURE: "ADD_LIKE_FAILURE",
  DELETE_LIKE_REQUEST: "DELETE_LIKE_REQUEST",
  DELETE_LIKE_SUCCESS: "DELETE_LIKE_SUCCESS",
  DELETE_LIKE_FAILURE: "DELETE_LIKE_FAILURE",
};

export const accountTypes = {
  LOAD_ACCOUNT_PROFILE_REQUEST: "LOAD_ACCOUNT_PROFILE_REQUEST",
  LOAD_ACCOUNT_PROFILE_SUCCESS: "LOAD_ACCOUNT_PROFILE_SUCCESS",
  LOAD_ACCOUNT_PROFILE_FAILURE: "LOAD_ACCOUNT_PROFILE_FAILURE",
  UPDATE_ACCOUNT_PROFILE_REQUEST: "UPDATE_ACCOUNT_PROFILE_REQUEST",
  UPDATE_ACCOUNT_PROFILE_SUCCESS: "UPDATE_ACCOUNT_PROFILE_SUCCESS",
  UPDATE_ACCOUNT_PROFILE_FAILURE: "UPDATE_ACCOUNT_PROFILE_FAILURE",
  DELETE_ACCOUNT_REQUEST: "DELETE_ACCOUNT_REQUEST",
  DELETE_ACCOUNT_SUCCESS: "DELETE_ACCOUNT_SUCCESS",
  DELETE_ACCOUNT_FAILURE: "DELETE_ACCOUNT_FAILURE",
  INITIALISE_ACCOUNT_REDUCER: "INITIALISE_ACCOUNT_REDUCER:",
};
